import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { IStateType } from '@/store'
import { getRadioDetail, getRadioProgram } from '../service/djradio-detail'

export const fetchRadioDetailDataAction = createAsyncThunk<
  void,
  number,
  { state: IStateType }
>('RadioDetailData', async (rid, { dispatch }) => {
  const res = await getRadioDetail(rid)
  dispatch(setRadioDetail(res.data))
})
export const fetchRadioProgramDataAction = createAsyncThunk<
  void,
  { rid: number; offset?: number; limit?: number; asc?: boolean },
  { state: IStateType }
>(
  'RadioProgramData',
  async ({ rid, offset = 0, limit = 100, asc = true }, { dispatch }) => {
    const res = await getRadioProgram(rid, offset, limit, asc)
    dispatch(setRadioProgram(res))
  }
)
const radioDetailSlice = createSlice({
  name: 'radioDetail',
  initialState: {
    radioDetail: {
      id: 1003727393,
      name: '爱的表达式',
      dj: {
        defaultAvatar: false,
        province: 440000,
        authStatus: 0,
        followed: false,
        avatarUrl:
          'http://p1.music.126.net/NhyPG30HBsKfjf6GtDiyGw==/109951167134538676.jpg',
        accountStatus: 0,
        gender: 2,
        city: 440100,
        birthday: 881984682000,
        userId: 552826049,
        userType: 0,
        nickname: '瓜瓜聊天室',
        signature:
          '实践派情感博主，用星盘、心理、哲学理解人生意义。看朋友圈or咨询：guaguasis',
        description: '',
        detailDescription: '',
        avatarImgId: 109951167134538670,
        backgroundImgId: 109951163315401460,
        backgroundUrl:
          'http://p1.music.126.net/tG9n2RlJ4elyqmkpNgzGvw==/109951163315401451.jpg',
        authority: 0,
        mutual: false,
        expertTags: null,
        experts: null,
        djStatus: 10,
        vipType: 0,
        remarkName: null,
        authenticationTypes: 0,
        avatarDetail: null,
        avatarImgIdStr: '109951167134538676',
        backgroundImgIdStr: '109951163315401451',
        anchor: false,
        rewardCount: 0,
        avatarImgId_str: '109951167134538676',
        canReward: false
      },
      picId: 109951169515350910,
      picUrl:
        'https://p1.music.126.net/xYX_7gpZWLRMkFju0uaczg==/109951169515350919.jpg',
      desc: '瓜瓜的聊天室，每周和你一起聊聊大家关心的情感/占星/人生议题和故事。\n咨询（是本人）：guaguasis\n（备用）：Rosieruru',
      subCount: 172,
      shareCount: 0,
      likedCount: 0,
      programCount: 85,
      commentCount: 0,
      createTime: 1713756355970,
      categoryId: 3,
      category: '情感',
      secondCategoryId: 469051,
      secondCategory: '恋爱婚姻',
      radioFeeType: 0,
      feeScope: 0,
      lastProgramCreateTime: 1716418764706,
      lastProgramId: 2544684732,
      rcmdText: '和你一起面对情感、成长等人生每一个命题',
      subed: false,
      commentDatas: [],
      feeInfo: null,
      unlockInfo: null,
      original: true,
      playCount: 0,
      privacy: false,
      disableShare: false,
      icon: null,
      activityInfo: null,
      toplistInfo: null,
      dynamic: false,
      labelDto: null,
      labels: null,
      detailRcmdTabOrpheus:
        'orpheus://rnpage?component=rn-podcast-voicelist-recmd&radioId=1003727393',
      toast: null,
      limitFreeToast: null
    },
    radioProgram: {
      count: 85,
      code: 200,
      programs: [
        {
          mainSong: {
            name: '“火象女”恋爱风格，受伤一百次也不长记性',
            id: 2158801344,
            position: 0,
            alias: [],
            status: 0,
            fee: 0,
            copyrightId: 0,
            disc: '',
            no: 0,
            artists: [
              {
                name: '瓜瓜聊天室',
                id: 0,
                picId: 0,
                img1v1Id: 0,
                briefDesc: '',
                picUrl:
                  'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                img1v1Url:
                  'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                albumSize: 0,
                alias: [],
                trans: '',
                musicSize: 0,
                topicPerson: 0
              }
            ],
            album: {
              name: null,
              id: 0,
              type: null,
              size: 0,
              picId: 0,
              blurPicUrl: null,
              companyId: 0,
              pic: 0,
              picUrl:
                'http://p2.music.126.net/0ju8ET1ApZSXfWacc4w49w==/109951169484091680.jpg',
              publishTime: 0,
              description: '',
              tags: '',
              company: null,
              briefDesc: '',
              artist: {
                name: '',
                id: 0,
                picId: 0,
                img1v1Id: 0,
                briefDesc: '',
                picUrl:
                  'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                img1v1Url:
                  'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                albumSize: 0,
                alias: [],
                trans: '',
                musicSize: 0,
                topicPerson: 0
              },
              songs: [],
              alias: [],
              status: 0,
              copyrightId: 0,
              commentThreadId: 'R_AL_3_0',
              artists: [
                {
                  name: '',
                  id: 0,
                  picId: 0,
                  img1v1Id: 0,
                  briefDesc: '',
                  picUrl:
                    'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                  img1v1Url:
                    'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                  albumSize: 0,
                  alias: [],
                  trans: '',
                  musicSize: 0,
                  topicPerson: 0
                }
              ],
              subType: null,
              transName: null,
              mark: 0
            },
            starred: false,
            popularity: 5,
            score: 5,
            starredNum: 0,
            duration: 1643572,
            playedNum: 0,
            dayPlays: 0,
            hearTime: 0,
            ringtone: null,
            crbt: null,
            audition: null,
            copyFrom: '',
            commentThreadId: 'R_SO_4_2158801344',
            rtUrl: null,
            ftype: 0,
            rtUrls: [],
            copyright: 1,
            transName: null,
            sign: null,
            mark: 0,
            noCopyrightRcmd: null,
            rtype: 0,
            rurl: null,
            mvid: 0,
            hMusic: null,
            mMusic: {
              name: null,
              id: 9202445147,
              size: 53631020,
              extension: 'mp3',
              sr: 44100,
              dfsId: 0,
              bitrate: 261000,
              playTime: 1643572,
              volumeDelta: 0
            },
            lMusic: {
              name: null,
              id: 9202445147,
              size: 53631020,
              extension: 'mp3',
              sr: 44100,
              dfsId: 0,
              bitrate: 261000,
              playTime: 1643572,
              volumeDelta: 0
            },
            bMusic: {
              name: null,
              id: 9202445147,
              size: 53631020,
              extension: 'mp3',
              sr: 44100,
              dfsId: 0,
              bitrate: 261000,
              playTime: 1643572,
              volumeDelta: 0
            },
            mp3Url: null
          },
          songs: null,
          dj: {
            defaultAvatar: false,
            province: 440000,
            authStatus: 0,
            followed: false,
            avatarUrl:
              'http://p1.music.126.net/NhyPG30HBsKfjf6GtDiyGw==/109951167134538676.jpg',
            accountStatus: 0,
            gender: 2,
            city: 440100,
            birthday: 881984682000,
            userId: 552826049,
            userType: 0,
            nickname: '瓜瓜聊天室',
            signature:
              '实践派情感博主，用星盘、心理、哲学理解人生意义。看朋友圈or咨询：guaguasis',
            description: '',
            detailDescription: '',
            avatarImgId: 109951167134538670,
            backgroundImgId: 109951163315401460,
            backgroundUrl:
              'http://p1.music.126.net/tG9n2RlJ4elyqmkpNgzGvw==/109951163315401451.jpg',
            authority: 0,
            mutual: false,
            expertTags: null,
            experts: null,
            djStatus: 10,
            vipType: 0,
            remarkName: null,
            authenticationTypes: 0,
            avatarDetail: null,
            avatarImgIdStr: '109951167134538676',
            backgroundImgIdStr: '109951163315401451',
            anchor: false,
            avatarImgId_str: '109951167134538676',
            brand: '爱的表达式'
          },
          blurCoverUrl:
            'http://music.163.com/api/dj/img/blur/109951169515350919',
          radio: {
            dj: null,
            category: '情感',
            secondCategory: '恋爱婚姻',
            buyed: false,
            price: 0,
            originalPrice: 0,
            discountPrice: null,
            purchaseCount: 0,
            lastProgramName: null,
            videos: null,
            finished: false,
            underShelf: false,
            liveInfo: null,
            playCount: 0,
            privacy: false,
            icon: null,
            manualTagsDTO: null,
            descPicList: null,
            replaceRadioId: 0,
            replaceRadio: null,
            shortName: null,
            dynamic: false,
            programCount: 85,
            picId: 109951169515350910,
            categoryId: 3,
            taskId: 0,
            subCount: 172,
            feeScope: 0,
            lastProgramId: 2544684732,
            picUrl:
              'https://p2.music.126.net/xYX_7gpZWLRMkFju0uaczg==/109951169515350919.jpg',
            lastProgramCreateTime: 1716418764706,
            radioFeeType: 0,
            intervenePicUrl:
              'https://p2.music.126.net/xYX_7gpZWLRMkFju0uaczg==/109951169515350919.jpg',
            intervenePicId: 109951169515350910,
            desc: '瓜瓜的聊天室，每周和你一起聊聊大家关心的情感/占星/人生议题和故事。\n咨询（是本人）：guaguasis\n（备用）：Rosieruru',
            createTime: 1713756355970,
            name: '爱的表达式',
            id: 1003727393,
            subed: false
          },
          duration: 1643572,
          authDTO: null,
          buyed: false,
          programDesc: [
            {
              type: 1,
              id: 0,
              content: '02:52 射手女：爱理念大于爱他本身',
              height: null,
              width: null,
              timeStamp: '02:52',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '09:27 白羊女：受一百次伤也不长记性',
              height: null,
              width: null,
              timeStamp: '09:27',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '18:14 狮子女：外在稳定内心慌得一批',
              height: null,
              width: null,
              timeStamp: '18:14',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '捉住瓜瓜（看朋友圈or咨询）：guaguasis',
              height: null,
              width: null,
              timeStamp: null,
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '（备用）：guaguaRosie',
              height: null,
              width: null,
              timeStamp: null,
              nestedData: null
            }
          ],
          h5Links: null,
          canReward: false,
          auditStatus: 10,
          videoInfo: null,
          score: 0,
          liveInfo: null,
          alg: null,
          disPlayStatus: null,
          auditDisPlayStatus: 1,
          categoryName: null,
          secondCategoryName: null,
          existLyric: false,
          djPlayRecordVo: null,
          recommended: false,
          icon: null,
          additionIconList: null,
          adIconInfo: null,
          replaceVoiceId: 0,
          replaceResource: null,
          songTimeStamps: null,
          classicRelationSong: null,
          specialTags: null,
          seqNo: null,
          mainTrackId: 2158801344,
          titbits: null,
          coverId: 109951169515350910,
          titbitImages: null,
          trackCount: 0,
          isPublish: true,
          channels: ['情感驿站'],
          categoryId: 3,
          commentThreadId: 'A_DJ_1_2544684732',
          createEventId: 0,
          listenerCount: 44,
          scheduledPublishTime: 1716418764706,
          serialNum: 85,
          bdAuditStatus: 2,
          secondCategoryId: 469051,
          smallLanguageAuditStatus: 0,
          coverUrl:
            'https://p2.music.126.net/xYX_7gpZWLRMkFju0uaczg==/109951169515350919.jpg',
          pubStatus: 1,
          programFeeType: 0,
          feeScope: 0,
          reward: false,
          subscribedCount: 0,
          privacy: false,
          description:
            '02:52 射手女：爱理念大于爱他本身\n09:27 白羊女：受一百次伤也不长记性\n18:14 狮子女：外在稳定内心慌得一批\n捉住瓜瓜（看朋友圈or咨询）：guaguasis\n（备用）：guaguaRosie',
          createTime: 1716418764706,
          name: '“火象女”恋爱风格，受伤一百次也不长记性',
          id: 2544684732,
          shareCount: 1,
          subscribed: false,
          likedCount: 0,
          commentCount: 0
        },
        {
          mainSong: {
            name: '我竟然是“控制型伴侣”？无条件的爱好难',
            id: 2156253821,
            position: 0,
            alias: [],
            status: 0,
            fee: 0,
            copyrightId: 0,
            disc: '',
            no: 0,
            artists: [
              {
                name: '瓜瓜聊天室',
                id: 0,
                picId: 0,
                img1v1Id: 0,
                briefDesc: '',
                picUrl:
                  'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                img1v1Url:
                  'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                albumSize: 0,
                alias: [],
                trans: '',
                musicSize: 0,
                topicPerson: 0
              }
            ],
            album: {
              name: null,
              id: 0,
              type: null,
              size: 0,
              picId: 0,
              blurPicUrl: null,
              companyId: 0,
              pic: 0,
              picUrl:
                'http://p2.music.126.net/0ju8ET1ApZSXfWacc4w49w==/109951169484091680.jpg',
              publishTime: 0,
              description: '',
              tags: '',
              company: null,
              briefDesc: '',
              artist: {
                name: '',
                id: 0,
                picId: 0,
                img1v1Id: 0,
                briefDesc: '',
                picUrl:
                  'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                img1v1Url:
                  'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                albumSize: 0,
                alias: [],
                trans: '',
                musicSize: 0,
                topicPerson: 0
              },
              songs: [],
              alias: [],
              status: 0,
              copyrightId: 0,
              commentThreadId: 'R_AL_3_0',
              artists: [
                {
                  name: '',
                  id: 0,
                  picId: 0,
                  img1v1Id: 0,
                  briefDesc: '',
                  picUrl:
                    'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                  img1v1Url:
                    'http://p2.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg',
                  albumSize: 0,
                  alias: [],
                  trans: '',
                  musicSize: 0,
                  topicPerson: 0
                }
              ],
              subType: null,
              transName: null,
              mark: 0
            },
            starred: false,
            popularity: 5,
            score: 5,
            starredNum: 0,
            duration: 2933922,
            playedNum: 0,
            dayPlays: 0,
            hearTime: 0,
            ringtone: null,
            crbt: null,
            audition: null,
            copyFrom: '',
            commentThreadId: 'R_SO_4_2156253821',
            rtUrl: null,
            ftype: 0,
            rtUrls: [],
            copyright: 1,
            transName: null,
            sign: null,
            mark: 0,
            noCopyrightRcmd: null,
            rtype: 0,
            rurl: null,
            mvid: 0,
            hMusic: null,
            mMusic: {
              name: null,
              id: 9173422621,
              size: 94395508,
              extension: 'mp3',
              sr: 44100,
              dfsId: 0,
              bitrate: 256000,
              playTime: 2933922,
              volumeDelta: 0
            },
            lMusic: {
              name: null,
              id: 9173422621,
              size: 94395508,
              extension: 'mp3',
              sr: 44100,
              dfsId: 0,
              bitrate: 256000,
              playTime: 2933922,
              volumeDelta: 0
            },
            bMusic: {
              name: null,
              id: 9173422621,
              size: 94395508,
              extension: 'mp3',
              sr: 44100,
              dfsId: 0,
              bitrate: 256000,
              playTime: 2933922,
              volumeDelta: 0
            },
            mp3Url: null
          },
          songs: null,
          dj: {
            defaultAvatar: false,
            province: 440000,
            authStatus: 0,
            followed: false,
            avatarUrl:
              'http://p1.music.126.net/NhyPG30HBsKfjf6GtDiyGw==/109951167134538676.jpg',
            accountStatus: 0,
            gender: 2,
            city: 440100,
            birthday: 881984682000,
            userId: 552826049,
            userType: 0,
            nickname: '瓜瓜聊天室',
            signature:
              '实践派情感博主，用星盘、心理、哲学理解人生意义。看朋友圈or咨询：guaguasis',
            description: '',
            detailDescription: '',
            avatarImgId: 109951167134538670,
            backgroundImgId: 109951163315401460,
            backgroundUrl:
              'http://p1.music.126.net/tG9n2RlJ4elyqmkpNgzGvw==/109951163315401451.jpg',
            authority: 0,
            mutual: false,
            expertTags: null,
            experts: null,
            djStatus: 10,
            vipType: 0,
            remarkName: null,
            authenticationTypes: 0,
            avatarDetail: null,
            avatarImgIdStr: '109951167134538676',
            backgroundImgIdStr: '109951163315401451',
            anchor: false,
            avatarImgId_str: '109951167134538676',
            brand: '爱的表达式'
          },
          blurCoverUrl:
            'http://music.163.com/api/dj/img/blur/109951169515350919',
          radio: {
            dj: null,
            category: '情感',
            secondCategory: '恋爱婚姻',
            buyed: false,
            price: 0,
            originalPrice: 0,
            discountPrice: null,
            purchaseCount: 0,
            lastProgramName: null,
            videos: null,
            finished: false,
            underShelf: false,
            liveInfo: null,
            playCount: 0,
            privacy: false,
            icon: null,
            manualTagsDTO: null,
            descPicList: null,
            replaceRadioId: 0,
            replaceRadio: null,
            shortName: null,
            dynamic: false,
            programCount: 85,
            picId: 109951169515350910,
            categoryId: 3,
            taskId: 0,
            subCount: 172,
            feeScope: 0,
            lastProgramId: 2544684732,
            picUrl:
              'https://p2.music.126.net/xYX_7gpZWLRMkFju0uaczg==/109951169515350919.jpg',
            lastProgramCreateTime: 1716418764706,
            radioFeeType: 0,
            intervenePicUrl:
              'https://p2.music.126.net/xYX_7gpZWLRMkFju0uaczg==/109951169515350919.jpg',
            intervenePicId: 109951169515350910,
            desc: '瓜瓜的聊天室，每周和你一起聊聊大家关心的情感/占星/人生议题和故事。\n咨询（是本人）：guaguasis\n（备用）：Rosieruru',
            createTime: 1713756355970,
            name: '爱的表达式',
            id: 1003727393,
            subed: false
          },
          duration: 2933922,
          authDTO: null,
          buyed: false,
          programDesc: [
            {
              type: 1,
              id: 0,
              content: '00:26 我忍不住对男朋友产生指责和批判',
              height: null,
              width: null,
              timeStamp: '00:26',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '03:30 怨气变成了自责，是不是我要求太高了？',
              height: null,
              width: null,
              timeStamp: '03:30',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '04:18 小马灵魂发问：“如果有一天你不爱我了怎么办？”',
              height: null,
              width: null,
              timeStamp: '04:18',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content:
                '07:50 被「控制欲」控制，无法接受男友不按我的标准生活和思考',
              height: null,
              width: null,
              timeStamp: '07:50',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '10:32 我并不是无条件爱一个人，我只是希望他跟我一样',
              height: null,
              width: null,
              timeStamp: '10:32',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '15:43 我们的情绪，都是关于自己的课题',
              height: null,
              width: null,
              timeStamp: '15:43',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '17:50 凡是我们用力紧紧抓住的东西，都会成为我们的困扰',
              height: null,
              width: null,
              timeStamp: '17:50',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '10:03 批判对方，是因为没有好好看见自己',
              height: null,
              width: null,
              timeStamp: '10:03',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '23:56 控制对方，是没有接纳对方的自由意志',
              height: null,
              width: null,
              timeStamp: '23:56',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '25:19 光喊口号并不能帮助对方变好',
              height: null,
              width: null,
              timeStamp: '25:19',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '27:39 控制型伴侣想要的是「盆景式爱情」',
              height: null,
              width: null,
              timeStamp: '27:39',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '32:02 情绪起落跟星盘运势的关系',
              height: null,
              width: null,
              timeStamp: '32:02',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '36:13 后续更新：向他敞开心扉，承认自己的疏远和控制',
              height: null,
              width: null,
              timeStamp: '36:13',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '45:37 放下执念，我终于轻松了',
              height: null,
              width: null,
              timeStamp: '45:37',
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '捉住瓜瓜（看朋友圈or咨询）：guaguasis',
              height: null,
              width: null,
              timeStamp: null,
              nestedData: null
            },
            {
              type: 1,
              id: 0,
              content: '(备用）：guaguaRosie',
              height: null,
              width: null,
              timeStamp: null,
              nestedData: null
            }
          ],
          h5Links: null,
          canReward: false,
          auditStatus: 10,
          videoInfo: null,
          score: 0,
          liveInfo: null,
          alg: null,
          disPlayStatus: null,
          auditDisPlayStatus: 1,
          categoryName: null,
          secondCategoryName: null,
          existLyric: false,
          djPlayRecordVo: null,
          recommended: false,
          icon: null,
          additionIconList: null,
          adIconInfo: null,
          replaceVoiceId: 0,
          replaceResource: null,
          songTimeStamps: null,
          classicRelationSong: null,
          specialTags: null,
          seqNo: null,
          mainTrackId: 2156253821,
          titbits: null,
          coverId: 109951169515350910,
          titbitImages: null,
          trackCount: 0,
          isPublish: true,
          channels: ['情感驿站'],
          categoryId: 3,
          commentThreadId: 'A_DJ_1_2544414470',
          createEventId: 0,
          listenerCount: 778,
          scheduledPublishTime: 1715774511759,
          serialNum: 84,
          bdAuditStatus: 2,
          secondCategoryId: 469051,
          smallLanguageAuditStatus: 0,
          coverUrl:
            'https://p2.music.126.net/xYX_7gpZWLRMkFju0uaczg==/109951169515350919.jpg',
          pubStatus: 1,
          programFeeType: 0,
          feeScope: 0,
          reward: false,
          subscribedCount: 0,
          privacy: false,
          description:
            '00:26 我忍不住对男朋友产生指责和批判\n03:30 怨气变成了自责，是不是我要求太高了？\n04:18 小马灵魂发问：“如果有一天你不爱我了怎么办？”\n07:50 被「控制欲」控制，无法接受男友不按我的标准生活和思考\n10:32 我并不是无条件爱一个人，我只是希望他跟我一样\n15:43 我们的情绪，都是关于自己的课题\n17:50 凡是我们用力紧紧抓住的东西，都会成为我们的困扰\n10:03 批判对方，是因为没有好好看见自己\n23:56 控制对方，是没有接纳对方的自由意志\n25:19 光喊口号并不能帮助对方变好\n27:39 控制型伴侣想要的是「盆景式爱情」\n32:02 情绪起落跟星盘运势的关系\n36:13 后续更新：向他敞开心扉，承认自己的疏远和控制\n45:37 放下执念，我终于轻松了\n捉住瓜瓜（看朋友圈or咨询）：guaguasis\n(备用）：guaguaRosie',
          createTime: 1715774511759,
          name: '我竟然是“控制型伴侣”？无条件的爱好难',
          id: 2544414470,
          shareCount: 0,
          subscribed: false,
          likedCount: 0,
          commentCount: 0
        }
      ],
      more: true
    }
  },
  reducers: {
    setRadioDetail(state, { payload }) {
      state.radioDetail = payload
    },
    setRadioProgram(state, { payload }) {
      state.radioProgram = payload
    }
  }
})
export const { setRadioDetail, setRadioProgram } = radioDetailSlice.actions
export default radioDetailSlice.reducer
