export type IradioDetailType = {
  id: number
  name: string
  dj: {
    defaultAvatar: boolean
    province: number
    authStatus: number
    followed: boolean
    avatarUrl: string
    accountStatus: number
    gender: number
    city: number
    birthday: number
    userId: number
    userType: number
    nickname: string
    signature: string
    description: string
    detailDescription: string
    avatarImgId: number
    backgroundImgId: number
    backgroundUrl: string
    authority: number
    mutual: boolean
    expertTags: any
    experts: any
    djStatus: number
    vipType: number
    remarkName: any
    authenticationTypes: number
    avatarDetail: any
    avatarImgIdStr: string
    backgroundImgIdStr: string
    anchor: boolean
    rewardCount: number
    avatarImgId_str: string
    canReward: boolean
  }
  picId: number
  picUrl: string
  desc: string
  subCount: number
  shareCount: number
  likedCount: number
  programCount: number
  commentCount: number
  createTime: number
  categoryId: number
  category: string
  secondCategoryId: number
  secondCategory: string
  radioFeeType: number
  feeScope: number
  lastProgramCreateTime: number
  lastProgramId: number
  rcmdText: string
  subed: boolean
  commentDatas: Array<any>
  feeInfo: any
  unlockInfo: any
  original: boolean
  playCount: number
  privacy: boolean
  disableShare: boolean
  icon: any
  activityInfo: any
  toplistInfo: any
  dynamic: boolean
  labelDto: any
  labels: any
  detailRcmdTabOrpheus: string
  toast: any
  limitFreeToast: any
}
export type radioProgramType = {
  count: number
  code: number
  programs: Array<{
    mainSong: {
      name: string
      id: number
      position: number
      alias: Array<any>
      status: number
      fee: number
      copyrightId: number
      disc: string
      no: number
      artists: Array<{
        name: string
        id: number
        picId: number
        img1v1Id: number
        briefDesc: string
        picUrl: string
        img1v1Url: string
        albumSize: number
        alias: Array<any>
        trans: string
        musicSize: number
        topicPerson: number
      }>
      album: {
        name: any
        id: number
        type: any
        size: number
        picId: number
        blurPicUrl: any
        companyId: number
        pic: number
        picUrl: string
        publishTime: number
        description: string
        tags: string
        company: any
        briefDesc: string
        artist: {
          name: string
          id: number
          picId: number
          img1v1Id: number
          briefDesc: string
          picUrl: string
          img1v1Url: string
          albumSize: number
          alias: Array<any>
          trans: string
          musicSize: number
          topicPerson: number
        }
        songs: Array<any>
        alias: Array<any>
        status: number
        copyrightId: number
        commentThreadId: string
        artists: Array<{
          name: string
          id: number
          picId: number
          img1v1Id: number
          briefDesc: string
          picUrl: string
          img1v1Url: string
          albumSize: number
          alias: Array<any>
          trans: string
          musicSize: number
          topicPerson: number
        }>
        subType: any
        transName: any
        mark: number
      }
      starred: boolean
      popularity: number
      score: number
      starredNum: number
      duration: number
      playedNum: number
      dayPlays: number
      hearTime: number
      ringtone: any
      crbt: any
      audition: any
      copyFrom: string
      commentThreadId: string
      rtUrl: any
      ftype: number
      rtUrls: Array<any>
      copyright: number
      transName: any
      sign: any
      mark: number
      noCopyrightRcmd: any
      rtype: number
      rurl: any
      mvid: number
      hMusic: any
      mMusic: {
        name: any
        id: number
        size: number
        extension: string
        sr: number
        dfsId: number
        bitrate: number
        playTime: number
        volumeDelta: number
      }
      lMusic: {
        name: any
        id: number
        size: number
        extension: string
        sr: number
        dfsId: number
        bitrate: number
        playTime: number
        volumeDelta: number
      }
      bMusic: {
        name: any
        id: number
        size: number
        extension: string
        sr: number
        dfsId: number
        bitrate: number
        playTime: number
        volumeDelta: number
      }
      mp3Url: any
    }
    songs: any
    dj: {
      defaultAvatar: boolean
      province: number
      authStatus: number
      followed: boolean
      avatarUrl: string
      accountStatus: number
      gender: number
      city: number
      birthday: number
      userId: number
      userType: number
      nickname: string
      signature: string
      description: string
      detailDescription: string
      avatarImgId: number
      backgroundImgId: number
      backgroundUrl: string
      authority: number
      mutual: boolean
      expertTags: any
      experts: any
      djStatus: number
      vipType: number
      remarkName: any
      authenticationTypes: number
      avatarDetail: any
      avatarImgIdStr: string
      backgroundImgIdStr: string
      anchor: boolean
      avatarImgId_str: string
      brand: string
    }
    blurCoverUrl: string
    radio: {
      dj: any
      category: string
      secondCategory: string
      buyed: boolean
      price: number
      originalPrice: number
      discountPrice: any
      purchaseCount: number
      lastProgramName: any
      videos: any
      finished: boolean
      underShelf: boolean
      liveInfo: any
      playCount: number
      privacy: boolean
      icon: any
      manualTagsDTO: any
      descPicList: any
      replaceRadioId: number
      replaceRadio: any
      shortName: any
      dynamic: boolean
      programCount: number
      picId: number
      categoryId: number
      taskId: number
      subCount: number
      feeScope: number
      lastProgramId: number
      picUrl: string
      lastProgramCreateTime: number
      radioFeeType: number
      intervenePicUrl: string
      intervenePicId: number
      desc: string
      createTime: number
      name: string
      id: number
      subed: boolean
    }
    duration: number
    authDTO: any
    buyed: boolean
    programDesc: Array<{
      type: number
      id: number
      content: string
      height: any
      width: any
      timeStamp?: string
      nestedData: any
    }>
    h5Links: any
    canReward: boolean
    auditStatus: number
    videoInfo: any
    score: number
    liveInfo: any
    alg: any
    disPlayStatus: any
    auditDisPlayStatus: number
    categoryName: any
    secondCategoryName: any
    existLyric: boolean
    djPlayRecordVo: any
    recommended: boolean
    icon: any
    additionIconList: any
    adIconInfo: any
    replaceVoiceId: number
    replaceResource: any
    songTimeStamps: any
    classicRelationSong: any
    specialTags: any
    seqNo: any
    mainTrackId: number
    titbits: any
    coverId: number
    titbitImages: any
    trackCount: number
    isPublish: boolean
    channels: Array<string>
    categoryId: number
    commentThreadId: string
    createEventId: number
    listenerCount: number
    scheduledPublishTime: number
    serialNum: number
    bdAuditStatus: number
    secondCategoryId: number
    smallLanguageAuditStatus: number
    coverUrl: string
    pubStatus: number
    programFeeType: number
    feeScope: number
    reward: boolean
    subscribedCount: number
    privacy: boolean
    description: string
    createTime: number
    name: string
    id: number
    shareCount: number
    subscribed: boolean
    likedCount: number
    commentCount: number
  }>
  more: boolean
}
export type IradioDetailState = {
  radioDetail: IradioDetailType
  radioProgram: radioProgramType
}
