export type djCatelistType = Array<{
  pic56x56Id: number
  pic96x96Id: number
  picPCWhite: number
  picPCBlack: number
  picWeb: number
  picIPad: number
  pic84x84Id: number
  pic56x56IdStr: string
  pic56x56Url: string
  pic96x96IdStr: string
  pic96x96Url: string
  pic84x84IdUrl: string
  picPCWhiteStr: string
  picPCWhiteUrl: string
  picPCBlackStr: string
  picPCBlackUrl: string
  picWebStr: string
  picWebUrl: string
  picMacId: string
  picMacUrl: string
  picUWPId: string
  picUWPUrl: string
  picIPadStr: string
  picIPadUrl: string
  name: string
  id: number
}>

export type djRecommendType = Array<{
  mainSong: {
    name: string
    id: number
    position: number
    alias: Array<any>
    status: number
    fee: number
    copyrightId: number
    disc: string
    no: number
    artists: Array<{
      name: string
      id: number
      picId: number
      img1v1Id: number
      briefDesc: string
      picUrl: string
      img1v1Url: string
      albumSize: number
      alias: Array<any>
      trans: string
      musicSize: number
      topicPerson: number
    }>
    album: {
      name?: string
      id: number
      type: any
      size: number
      picId: number
      blurPicUrl?: string
      companyId: number
      pic: number
      picUrl: string
      publishTime: number
      description: string
      tags: string
      company: any
      briefDesc: string
      artist: {
        name: string
        id: number
        picId: number
        img1v1Id: number
        briefDesc: string
        picUrl: string
        img1v1Url: string
        albumSize: number
        alias: Array<any>
        trans: string
        musicSize: number
        topicPerson: number
      }
      songs: Array<any>
      alias: Array<any>
      status: number
      copyrightId: number
      commentThreadId: string
      artists: Array<{
        name: string
        id: number
        picId: number
        img1v1Id: number
        briefDesc: string
        picUrl: string
        img1v1Url: string
        albumSize: number
        alias: Array<any>
        trans: string
        musicSize: number
        topicPerson: number
      }>
      subType: any
      transName: any
      mark: number
      picId_str?: string
    }
    starred: boolean
    popularity: number
    score: number
    starredNum: number
    duration: number
    playedNum: number
    dayPlays: number
    hearTime: number
    ringtone: any
    crbt: any
    audition: any
    copyFrom: string
    commentThreadId: string
    rtUrl: any
    ftype: number
    rtUrls: Array<any>
    copyright: number
    transName: any
    sign: any
    mark: number
    noCopyrightRcmd: any
    hMusic?: {
      name: any
      id: number
      size: number
      extension: string
      sr: number
      dfsId: number
      bitrate: number
      playTime: number
      volumeDelta: number
    }
    mMusic?: {
      name: any
      id: number
      size: number
      extension: string
      sr: number
      dfsId: number
      bitrate: number
      playTime: number
      volumeDelta: number
    }
    lMusic: {
      name: any
      id: number
      size: number
      extension: string
      sr: number
      dfsId: number
      bitrate: number
      playTime: number
      volumeDelta: number
    }
    rtype: number
    rurl: any
    mvid: number
    bMusic: {
      name: any
      id: number
      size: number
      extension: string
      sr: number
      dfsId: number
      bitrate: number
      playTime: number
      volumeDelta: number
    }
    mp3Url: any
  }
  songs: any
  dj: {
    defaultAvatar: boolean
    province: number
    authStatus: number
    followed: boolean
    avatarUrl: string
    accountStatus: number
    gender: number
    city: number
    birthday: number
    userId: number
    userType: number
    nickname: string
    signature: string
    description: string
    detailDescription: string
    avatarImgId: number
    backgroundImgId: number
    backgroundUrl: string
    authority: number
    mutual: boolean
    expertTags: any
    experts: any
    djStatus: number
    vipType: number
    remarkName: any
    authenticationTypes: number
    avatarDetail: any
    avatarImgIdStr: string
    backgroundImgIdStr: string
    anchor: boolean
    avatarImgId_str?: string
    brand: string
  }
  blurCoverUrl: string
  radio: {
    dj: any
    category: string
    secondCategory: string
    buyed: boolean
    price: number
    originalPrice: number
    discountPrice: any
    purchaseCount: number
    lastProgramName: any
    videos: any
    finished: boolean
    underShelf: boolean
    liveInfo: any
    playCount: number
    privacy: boolean
    icon: any
    manualTagsDTO: any
    descPicList?: Array<{
      type: number
      id: number
      content: string
      height: any
      width: any
      timeStamp: any
      nestedData?: {
        textList?: Array<{
          text: string
          attributes: any
        }>
        attributes: any
      }
    }>
    replaceRadioId: number
    replaceRadio: any
    shortName: any
    programCount: number
    intervenePicId: number
    picId: number
    categoryId: number
    taskId: number
    intervenePicUrl: string
    subCount: number
    feeScope: number
    picUrl: string
    lastProgramId: number
    lastProgramCreateTime: number
    radioFeeType: number
    dynamic: boolean
    desc: string
    createTime: number
    name: string
    id: number
    subed: boolean
  }
  duration: number
  authDTO: any
  buyed: boolean
  programDesc: any
  h5Links: any
  canReward: boolean
  auditStatus: number
  videoInfo: any
  score: number
  liveInfo: any
  alg: string
  disPlayStatus: any
  auditDisPlayStatus: number
  categoryName: any
  secondCategoryName: any
  existLyric: boolean
  djPlayRecordVo: any
  recommended: boolean
  icon: any
  additionIconList: any
  adIconInfo: any
  replaceVoiceId: number
  replaceResource: any
  songTimeStamps: any
  classicRelationSong: any
  specialTags: any
  seqNo: any
  subscribedCount: number
  reward: boolean
  titbits: any
  serialNum: number
  createEventId: number
  listenerCount: number
  scheduledPublishTime: number
  channels: Array<string>
  categoryId: number
  commentThreadId: string
  coverId: number
  privacy: boolean
  coverUrl: string
  smallLanguageAuditStatus: number
  bdAuditStatus: number
  secondCategoryId: number
  pubStatus: number
  mainTrackId: number
  programFeeType: number
  feeScope: number
  trackCount: number
  isPublish: boolean
  titbitImages: any
  description: string
  createTime: number
  name: string
  id: number
  reason: string
  subscribed: boolean
  shareCount: number
  likedCount: number
  commentCount: number
}>

export type djRankingType = Array<{
  program: {
    mainSong: {
      name: string
      id: number
      position: number
      alias: Array<any>
      status: number
      fee: number
      copyrightId: number
      disc: string
      no: number
      artists: Array<{
        name: string
        id: number
        picId: number
        img1v1Id: number
        briefDesc: string
        picUrl: string
        img1v1Url: string
        albumSize: number
        alias: Array<any>
        trans: string
        musicSize: number
        topicPerson: number
      }>
      album: {
        name?: string
        id: number
        type: any
        size: number
        picId: number
        blurPicUrl?: string
        companyId: number
        pic: number
        picUrl: string
        publishTime: number
        description: string
        tags: string
        company: any
        briefDesc: string
        artist: {
          name: string
          id: number
          picId: number
          img1v1Id: number
          briefDesc: string
          picUrl: string
          img1v1Url: string
          albumSize: number
          alias: Array<any>
          trans: string
          musicSize: number
          topicPerson: number
        }
        songs: Array<any>
        alias: Array<any>
        status: number
        copyrightId: number
        commentThreadId: string
        artists: Array<{
          name: string
          id: number
          picId: number
          img1v1Id: number
          briefDesc: string
          picUrl: string
          img1v1Url: string
          albumSize: number
          alias: Array<any>
          trans: string
          musicSize: number
          topicPerson: number
        }>
        subType: any
        transName: any
        mark: number
        picId_str?: string
      }
      starred: boolean
      popularity: number
      score: number
      starredNum: number
      duration: number
      playedNum: number
      dayPlays: number
      hearTime: number
      ringtone: any
      crbt: any
      audition: any
      copyFrom: string
      commentThreadId: string
      rtUrl: any
      ftype: number
      rtUrls: Array<any>
      copyright: number
      transName: any
      sign: any
      mark: number
      noCopyrightRcmd: any
      hMusic?: {
        name: any
        id: number
        size: number
        extension: string
        sr: number
        dfsId: number
        bitrate: number
        playTime: number
        volumeDelta: number
      }
      mMusic?: {
        name: any
        id: number
        size: number
        extension: string
        sr: number
        dfsId: number
        bitrate: number
        playTime: number
        volumeDelta: number
      }
      lMusic: {
        name: any
        id: number
        size: number
        extension: string
        sr: number
        dfsId: number
        bitrate: number
        playTime: number
        volumeDelta: number
      }
      rtype: number
      rurl: any
      mvid: number
      bMusic: {
        name: any
        id: number
        size: number
        extension: string
        sr: number
        dfsId: number
        bitrate: number
        playTime: number
        volumeDelta: number
      }
      mp3Url: any
    }
    songs: any
    dj: {
      defaultAvatar: boolean
      province: number
      authStatus: number
      followed: boolean
      avatarUrl: string
      accountStatus: number
      gender: number
      city: number
      birthday: number
      userId: number
      userType: number
      nickname: string
      signature: string
      description: string
      detailDescription: string
      avatarImgId: number
      backgroundImgId: number
      backgroundUrl: string
      authority: number
      mutual: boolean
      expertTags?: Array<string>
      experts?: {
        '2': string
      }
      djStatus: number
      vipType: number
      remarkName: any
      authenticationTypes: number
      avatarDetail: any
      avatarImgIdStr: string
      backgroundImgIdStr: string
      anchor: boolean
      avatarImgId_str: string
      brand: string
    }
    blurCoverUrl: string
    radio: {
      dj: any
      category: string
      secondCategory: string
      buyed: boolean
      price: number
      originalPrice: number
      discountPrice: any
      purchaseCount: number
      lastProgramName: any
      videos: any
      finished: boolean
      underShelf: boolean
      liveInfo: any
      playCount: number
      privacy: boolean
      icon: any
      manualTagsDTO: any
      descPicList?: Array<{
        type: number
        id: number
        content: string
        height: any
        width: any
        timeStamp: any
        nestedData: {
          textList?: Array<{
            text: string
            attributes: any
          }>
          attributes: any
        }
      }>
      replaceRadioId: number
      replaceRadio: any
      dynamic: boolean
      programCount: number
      shortName: any
      picId: number
      categoryId: number
      taskId: number
      subCount: number
      picUrl: string
      feeScope: number
      lastProgramId: number
      lastProgramCreateTime: number
      radioFeeType: number
      intervenePicUrl: string
      intervenePicId: number
      name: string
      id: number
      desc: string
      createTime: number
      subed: boolean
    }
    duration: number
    authDTO: any
    buyed: boolean
    programDesc: any
    h5Links: any
    canReward: boolean
    auditStatus: number
    videoInfo: any
    score: number
    liveInfo: any
    alg: any
    disPlayStatus: any
    auditDisPlayStatus: number
    categoryName: any
    secondCategoryName: any
    existLyric: boolean
    djPlayRecordVo: any
    recommended: boolean
    icon: any
    additionIconList: any
    adIconInfo: any
    replaceVoiceId: number
    replaceResource: any
    songTimeStamps: any
    classicRelationSong: any
    specialTags: any
    seqNo: any
    listenerCount: number
    serialNum: number
    createEventId: number
    scheduledPublishTime: number
    channels: Array<string>
    titbitImages: any
    trackCount: number
    isPublish: boolean
    categoryId: number
    commentThreadId: string
    coverId: number
    smallLanguageAuditStatus: number
    coverUrl: string
    bdAuditStatus: number
    secondCategoryId: number
    pubStatus: number
    mainTrackId: number
    programFeeType: number
    titbits: any
    feeScope: number
    subscribedCount: number
    reward: boolean
    privacy: boolean
    name: string
    id: number
    description: string
    createTime: number
    subscribed: boolean
    shareCount: number
    likedCount: number
    commentCount: number
  }
  rank: number
  lastRank: number
  score: number
  programFeeType: number
}>
export type djRecommendByTypeType = Array<{
  dj: {
    defaultAvatar: boolean
    province: number
    authStatus: number
    followed: boolean
    avatarUrl: string
    accountStatus: number
    gender: number
    city: number
    birthday: number
    userId: number
    userType: number
    nickname: string
    signature: string
    description: string
    detailDescription: string
    avatarImgId: number
    backgroundImgId: number
    backgroundUrl: string
    authority: number
    mutual: boolean
    expertTags: any
    experts: any
    djStatus: number
    vipType: number
    remarkName: any
    authenticationTypes: number
    avatarDetail: any
    avatarImgIdStr: string
    backgroundImgIdStr: string
    anchor: boolean
    avatarImgId_str: string
  }
  category: string
  secondCategory: string
  buyed: boolean
  price: number
  originalPrice: number
  discountPrice: any
  purchaseCount: number
  lastProgramName: string
  videos: any
  finished: boolean
  underShelf: boolean
  liveInfo: any
  playCount: number
  privacy: boolean
  icon: any
  manualTagsDTO: any
  descPicList?: Array<{
    type: number
    id: number
    content: string
    height: any
    width: any
    timeStamp: any
    nestedData: {
      textList?: Array<{
        text: string
        attributes: any
      }>
      attributes: any
    }
  }>
  replaceRadioId: number
  replaceRadio: any
  radioFeeType: number
  picId: number
  categoryId: number
  taskId: number
  shortName: any
  intervenePicUrl: string
  programCount: number
  subCount: number
  feeScope: number
  lastProgramId: number
  picUrl: string
  lastProgramCreateTime: number
  intervenePicId: number
  dynamic: boolean
  desc: string
  createTime: number
  name: string
  id: number
  rcmdtext: string
  subed: boolean
  lastUpdateProgramName: string
}>
export type djRadioListType = {
  djRadios: Array<{
    dj: {
      defaultAvatar: boolean
      province: number
      authStatus: number
      followed: boolean
      avatarUrl: string
      accountStatus: number
      gender: number
      city: number
      birthday: number
      userId: number
      userType: number
      nickname: string
      signature: string
      description: string
      detailDescription: string
      avatarImgId: number
      backgroundImgId: number
      backgroundUrl: string
      authority: number
      mutual: boolean
      expertTags?: Array<string>
      experts?: {
        '1': string
      }
      djStatus: number
      vipType: number
      remarkName: any
      authenticationTypes: number
      avatarDetail?: {
        userType: number
        identityLevel: number
        identityIconUrl: string
      }
      avatarImgIdStr: string
      backgroundImgIdStr: string
      anchor: boolean
      avatarImgId_str?: string
    }
    category: string
    secondCategory: string
    buyed: boolean
    price: number
    originalPrice: number
    discountPrice: any
    purchaseCount: number
    lastProgramName: string
    videos: any
    finished: boolean
    underShelf: boolean
    liveInfo: any
    playCount: number
    privacy: boolean
    icon: any
    manualTagsDTO: any
    descPicList?: Array<{
      type: number
      id: number
      content: string
      height: any
      width: any
      timeStamp: any
      nestedData?: {
        textList: Array<{
          text: string
          attributes: any
        }>
        attributes: any
      }
    }>
    replaceRadioId: number
    replaceRadio: any
    shortName: any
    picId: number
    categoryId: number
    taskId: number
    programCount: number
    subCount: number
    feeScope: number
    lastProgramId: number
    picUrl: string
    lastProgramCreateTime: number
    radioFeeType: number
    intervenePicUrl: string
    intervenePicId: number
    dynamic: boolean
    name: string
    id: number
    desc: string
    createTime: number
    rcmdtext: string
    subed: boolean
  }>
  hasMore: boolean
  count: number
  code: number
}

export type IDjradioState = {
  djCatelist: djCatelistType
  djRecommend: djRecommendType
  djRanking: djRankingType
  djRecommendByType: djRecommendByTypeType
  djRadioList: djRadioListType
}
